### ISSUE TITLE
Does this make a website work on mobile?

### ISSUE THREAD

**Issue by dogmydog** [silvermine/videojs-chromecast#104]
I'm trying to make this website player cast from mobile phone to chromecast.
www.tamandua.tv.br

But I can't see the cast button on iOS or android? Is it possible?
Thanks,

**Comment by jthomerson** [comment]
Sorry @dogmydog but we don't have the resources to provide user support. This plugin adds a Chromecast button to the VideoJS interface when you have it configured properly and are using it on devices and browsers that support Chromecast.
