### ISSUE TITLE
Add option to disable automatic insertion of Chromecast button into the player's control bar

### ISSUE THREAD

**Issue by yokuze** [silvermine/videojs-chromecast#11]
We should add a configuration option that allows users to disable the automatic insertion of the Chromecast button into the player's control bar.

Plugin users may want to specify where the Chromecast button appears in the player UI's component hierarchy using Video.js configuration options. With the way the plugin is now, the Chromecast button will be inserted into the control bar if the plugin does not find it at the root level of the `controlBar` component. If a plugin user specifies the Chromecast button to appear nested within an element in the `controlBar`, for example, the plugin will insert another Chromecast button at the root `controlBar` level.

**Comment by yokuze** [comment]
This issue was addressed with #12

**Comment by dds05** [comment]
How can I move the chrome-cast button outside of controlBar?
