### ISSUE TITLE
Playing local files

### ISSUE THREAD

**Issue by gsfioravanti** [silvermine/videojs-chromecast#114]
We are testing out this plugin for use in our apps, and have been able to successfully play remote video files loaded from our CDN urls, but not able to get local video files packaged within the app to cast.

Can this plugin play local files?  Or is there a workaround for playing local files?

**Comment by kontrollanten** [comment]
I don't think it's possible at all with Cast SDK to stream local files. https://stackoverflow.com/questions/24708560/cast-sdk-using-local-files

**Comment by jthomerson** [comment]
Thanks @kontrollanten
