### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by edgarsn** [silvermine/videojs-chromecast#128]
Hello!

First of all, thank you all for maintaining this package.

It's more than a 1 year since last tag. There are some changes made since then, especially ES6 support  (#98) which is a blocker in my case .

Could you please release a new tag, so we can use latest changes?

@jthomerson @yokuze

**Comment by dwassing** [comment]
I would like to emphasize this as well. I am facing the exact same issue with the ES6 support. Would absolutely love if you could cut a new version. Thanks!

**Comment by yokuze** [comment]
[We just published v1.3.4 with these changes.](https://github.com/silvermine/videojs-chromecast/releases/tag/v1.3.4)
