### ISSUE TITLE
Using plugin in a SvelteKit app

### ISSUE THREAD

**Issue by Lootwig** [silvermine/videojs-chromecast#134]
Is there a way to integrate this (and the airplay) plugin with svelte, i.e. without needing to call `require('...')` which is not supported?

**Comment by gkatsev** [comment]
this plugin only exposes commonjs files. From googling around, Svelte uses Vite under the hood for building, so, loading in `vite-plugin-commonjs` sounds like it'll address the issue: https://github.com/originjs/vite-plugins/tree/main/packages/vite-plugin-commonjs#commonjs-module-in-node_modules

**Comment by Lootwig** [comment]
Thanks to [this very helpful redditor](https://www.reddit.com/r/sveltejs/comments/wxkxzz/comment/ilrkbr7/?utm_source=share&utm_medium=web2x&context=3), I was able to get chromecast running:

```
import videojsChromecast from '@silvermine/videojs-chromecast';
videojsChromecast(videojs);
```
