### ISSUE TITLE
videojs.getComponent is not a function

### ISSUE THREAD

**Issue by The-web-wolf** [silvermine/videojs-chromecast#146]
Hello, I started tried using this plugin on my vue app and I constantly get this error videojs.getComponent is not a function, other plugins such as https://www.npmjs.com/package/videojs-overlay works fine.

I get this error on chromecast and airplay plugins both, I guess this has something to do with version compatibility? I'm unsure, I have reproduced this error on a sandbox, kindly take a look. 

https://codesandbox.io/s/awesome-varahamihira-7ixwhw

**Comment by yokuze** [comment]
Thank you for the MVCE/repro.

This isn't an issue with the plugin. This section of the docs explains that when you import the plugin directly, you need to call the imported function and pass in `videojs` to register the plugin: https://github.com/silvermine/videojs-chromecast#providing-initialization-options-via-require Granted, those docs use `require`, but the principle is the same with `import`.

Here's an updated Code Sandbox link: https://codesandbox.io/s/serverless-glitter-7xy64v
