### ISSUE TITLE
Support Video.js 8.x

### ISSUE THREAD

**Issue by ToshY** [silvermine/videojs-chromecast#147]
## Problem

Upgrading VideoJS from 7.20.3 to 8.0.2 I got dependency conflicts, as apparently its locked between 6 and 8

```json
  "peerDependencies": {
    "video.js": ">= 6 < 8"
  }
```

The README however states that its for [versions 6+](https://github.com/silvermine/videojs-chromecast#what-is-it).

## Expected solution

~~No dependency conflict.~~

Rewriting to be compatible with to 8.X: Migration guide [VideoJS 7 to 8](https://videojs.com/guides/videojs-7-to-8/):

**Comment by SoLoR1** [comment]
Even if there wouldnt be dependency conflict it would not work because: 

ideo.min.js:12 
        
       VIDEOJS: WARN: videojs.extend is deprecated as of Video.js 7.22.0 and will be removed in Video.js 8.0.0
(anonymous) @ video.min.js:12
n.warn @ video.min.js:12
ir.extend @ video.min.js:20
module.exports @ silvermine-videojs-chromecast.min.js:3704
module.exports @ silvermine-videojs-chromecast.min.js:3790
68../index @ silvermine-videojs-chromecast.min.js:3820
o @ silvermine-videojs-chromecast.min.js:17
r @ silvermine-videojs-chromecast.min.js:24
(anonymous) @ silvermine-videojs-chromecast.min.js:28

So it needs more then just solve dependency conflict.

**Comment by ToshY** [comment]
> Even if there wouldnt be dependency conflict it would not work because:
> 
> ```
> video.min.js:12 
>         
>        VIDEOJS: WARN: videojs.extend is deprecated as of Video.js 7.22.0 and will be removed in Video.js 8.0.0
> (anonymous) @ video.min.js:12
> n.warn @ video.min.js:12
> ir.extend @ video.min.js:20
> module.exports @ silvermine-videojs-chromecast.min.js:3704
> module.exports @ silvermine-videojs-chromecast.min.js:3790
> 68../index @ silvermine-videojs-chromecast.min.js:3820
> o @ silvermine-videojs-chromecast.min.js:17
> r @ silvermine-videojs-chromecast.min.js:24
> (anonymous) @ silvermine-videojs-chromecast.min.js:28
> ```

I am aware of this, that's why I added a link to the migration guide which also denotes `extend` being [deprecated](https://videojs.com/guides/videojs-7-to-8/#videojsextend) in 8.x.

I will update the desired solution so it contains that it requires migration as well.

**Comment by xSignificant** [comment]
Any updates?

**Comment by ToshY** [comment]
@xSignificant No 🙁

**Comment by ToshY** [comment]
@jthomerson 

Could you please take a look at this? Seems @ericfortmeyer has already created PRs for both the [chromecast](https://github.com/silvermine/videojs-chromecast/pull/153) as well as the [airplay](https://github.com/silvermine/videojs-airplay/pull/44) plugin.

**Comment by yokuze** [comment]
This is addressed in https://github.com/silvermine/videojs-chromecast/pull/153

**Comment by ToshY** [comment]
@yokuze is it possible to tag a new release?
