### ISSUE TITLE
chromecastSessionManager not defined?

### ISSUE THREAD

**Issue by DanielRHarris** [silvermine/videojs-chromecast#15]
Hi,

Not sure what if I'm setting this up incorrectly, or if I've run into a bug. It seems as if chromecastSessionManager isn't being defined. I've added chromecast first in the techOrder, and into the list of plugins. Using Video.js 6.7.1

Here's the error I'm getting in the console:
Uncaught TypeError: Cannot read property 'getRemotePlayer' of undefined
    at new constructor (silvermine-videojs-chromecast.js:2305)
    at e.loadTech_ (video.min.js:6)
    at e.reset (video.min.js:6)
    at loadNextVideoSegment (player.js:58)
    at e.<anonymous> (player.js:39)
    at r (video.min.js:2)

Thanks for the assist!

**Comment by jthomerson** [comment]
@DanielRHarris can you provide a codepen or some similar minimal testcase that shows exactly what you're doing so we can reproduce the error? Also, we are on the 6.2.x version of VideoJS, so we've developed and tested the Chromecast plugin with that. You may want to verify if this happens with that version of VideoJS as well. We should still fix it if it's a later version, but that would help us verify where to look.

**Comment by DanielRHarris** [comment]
Found the problem -- I had been calling reset() in the playlist handling code I was using (it fixed some captions bug as I recall). Removed it and everything started to work perfectly. Sorry for the trouble, and thanks for the assist!

**Comment by anhminh10a2hoa** [comment]
Have you fixed this problem @DanielRHarris
