### ISSUE TITLE
More frequent releases | Create a new tag

### ISSUE THREAD

**Issue by ToshY** [silvermine/videojs-chromecast#171]
@jthomerson  @yokuze @izkmdz 

I'd like to see more frequent releases. Majority of the time PRs get merged but no new tags are created. As a user I occasionally mention maintainers in issues/PRs in the hope they see it, but lots of times it takes months before even gets noticed or delegated to the right person, and even longer before it gets merged (e.g. https://github.com/silvermine/videojs-chromecast/pull/118).

With new fixes/changes in the current `master` branch, it would be very much appreciated if a maintainer could create a new tag.

> **Note**
> The same goes for [silvermine/videojs-airplay](https://github.com/silvermine/videojs-airplay)

**Comment by ToshY** [comment]
@jthomerson @yokuze @izkmdz ping

**Comment by yokuze** [comment]
We just published [v1.5.0](https://github.com/silvermine/videojs-chromecast/compare/v1.4.1...v1.5.0).

I understand that the frequency with which we are able to get to reviewing and merging PRs and creating releases is not ideal. However, we are doing the best that we can with the limited resources we have to devote to these repos, and we will continue to do so.

**Comment by ToshY** [comment]
Hey @yokuze 👋 

I really appreciate the dedication all of you put into maintaining these repos! Keep up the good work 🥇
