### ISSUE TITLE
Error: playbackRate is not a function

### ISSUE THREAD

**Issue by yokuze** [silvermine/videojs-chromecast#25]
While casting an HLS media item, this error is logged in the console periodically:

```
VIDEOJS: ERROR: TypeError: _this2.tech_.playbackRate is not a function
```

This is because the [ChromecastTech](https://github.com/silvermine/videojs-chromecast/blob/master/src/js/tech/ChromecastTech.js) class does not implement a `playbackRate` function.

**Comment by jthomerson** [comment]
Fixed in #26
