### ISSUE TITLE
If can't import then can repo be added to cdnjs

### ISSUE THREAD

**Issue by daveferrara1** [silvermine/videojs-chromecast#27]
It would be helpful if the releases were available on https://cdnjs.com. Then we could get the files from a cdn. cdnjs is free too!

I found I could not merely instantiate the plugin with a plugins object addition and an import statement like other plugins. I had to include the dist file in my head to get it to work.

Example:
```
plugins: {
            chromecast:{
              receiverAppID:'3x2083xxxx',
              addButtonToControlBar: false,
            },
```
followed by an import statement of:

```
import 'videojs-hotkeys';
// more plugins.
import '@silvermine/videojs-chromecast';
```

Helpful links.
https://github.com/cdnjs/cdnjs
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md

**Comment by daveferrara1** [comment]
I guess I am looking for the plugin to either be able to be imported and no addition to head tag, or the repo get added to cdnjs.

**Comment by jthomerson** [comment]
@daveferrara1 I'm assuming you closed it because it's already available on unpkg.com? Or for some other reason?

**Comment by daveferrara1** [comment]
Always for get that stuff is available o unpkg. I just realized if I wasn't going to use require I could just do:

`import chromecast from '@silvermine/videojs-chromecast';
chromecast(videojs);
`
