### ISSUE TITLE
HLS Live playback pauses after 45 seconds when casting.

### ISSUE THREAD

**Issue by daveferrara1** [silvermine/videojs-chromecast#28]
Got the plugin working great. Our live linear channels however error after what seems like exactly 45 seconds. If we use default receiver, same result.

**Comment by daveferrara1** [comment]
isolated my playback issues with this call to triggerReady().  If comment it out, I get uninterrupted playback, however the player itself I can no longer click any controls. Only the chrome browser plugin can pause and adjust volume.
 
```
 if (!this._hasPlayedAnyItem) {
               // `triggerReady` is required here to notify the Video.js player that the
               // Tech has been initialized and is ready.
               this.triggerReady();
            }
```

**Comment by daveferrara1** [comment]
Give this a go:  https://dev.pac-12.com/live/pac-12-live-press-conferences

**Comment by daveferrara1** [comment]
Possible one of my plugins is the culprit after that triggerReady() is called. Thanks for at least thinking about my problem.

**Comment by daveferrara1** [comment]
Thanks. I certainly set myself up for that response. Looks like first glance nothing jumped out at you. I'll follow up.

**Comment by daveferrara1** [comment]
The issue arises when we initialize the errors plugin:
https://github.com/brightcove/videojs-errors

If this plugin is initialized there is a timeout that is not satisfied when we cast.

Just initializing it with: 
```
plugins: {
 errors: {}
}
```

This will cause the error. Its 45 seconds because the `videojs("pac12-vjs-player").errors.timeout()` is set for for the 45 by default.

**Comment by jthomerson** [comment]
Great. Closing this since I assume you need to work out the issue with the errors plugin. Feel free to re-open this if you pinpoint that there's actually a change needed here.

**Comment by daveferrara1** [comment]
You may want to add a known issue to the readme listing the fact that this plugin doesn't work with the errors plugin out of the box now that I have notified you.

I suggest maybe adding a list of what plugins your testing with. If everything is only working on your simplified MCVE you'l likely see more issues opened in the past. Demo version even better. The an basic `videojs.getAllPlayers()` can answer a lot of questions for folks.

**Comment by jthomerson** [comment]
Sorry @daveferrara1, but I don't feel we need a list of plugins that we are or aren't compatible with at this time. Right now we still don't have an MCVE that even demonstrates the error you're reporting, so it's not possible for us to verify the assertion. Also, there are so many factors that go into a "compatibility" list: what version of this plugin, of video.js, of the other plugin(s), settings, configuration, HLS vs VOD, etc, etc. Plus, say that they fix the bug that's causing the incompatibility - then do we need to update our docs?

I appreciate the thought you put into it, but I'm hoping that Google / GitHub searches and this issue will be sufficient for if someone else encounters this error. If you find any other issues, let us know.
