### ISSUE TITLE
Add missing required Tech methods

### ISSUE THREAD

**Issue by yokuze** [silvermine/videojs-chromecast#41]
While investigating #30 and #32, I found that there are several functions that Video.js requires a custom [Tech](https://docs.videojs.com/tech) to implement that are [not documented](https://docs.videojs.com/tutorial-tech_.html#required-methods).

I attempted to make a comprehensive list of required methods and submitted it to Video.js here: https://github.com/videojs/video.js/issues/5737

Additionally, it was unclear what values should be returned for the `seekable` and `buffered` functions because that information is not available via the Chromecast API. I asked Video.js what they thought those functions should return, and their response is documented here: https://github.com/videojs/video.js/issues/5742

This issue is a request to add the missing `Tech` functions to the `ChromecastTech`.

You can see a demonstration of the error that's thrown when a player function that delegates to a missing Tech function is called here: https://codepen.io/mluedke/pen/zyaVjX

**Comment by stevendesu** [comment]
https://github.com/silvermine/videojs-chromecast/pull/43
