### ISSUE TITLE
DASH AudioStream Selection

### ISSUE THREAD

**Issue by woellij** [silvermine/videojs-chromecast#47]
Hi,

thanks for your helpful plugin.

Yet, we're facing the issue, that selecting an audio-stream from a DASH source during casting, is not reflected onto the chromecast.

Do you know, whether the cast protocol allows such a thing, or whether it would be possible do re-send the source with the selected audio stream and re-start from the current position?

Greeting

**Comment by jthomerson** [comment]
Sorry, we haven't tested it with DASH streams since we're not using DASH at this point. Please add any other details you find to this issue, and feel free to open a PR if you find something that can be improved.
