### ISSUE TITLE
It is possible to adjust the style of the chromecast subtitles (CC) based on the subtitle(CC) menu of videojs.

### ISSUE THREAD

**Issue by raestrada95** [silvermine/videojs-chromecast#49]
Hello, as the title says It is possible to adjust the style of the chromecast subtitles (CC) based on the subtitle(CC) menu of videojs seen in some applications of android that allows to adjust the design of the subitutles but I do not know if that function could be added.

I leave an example of HLS video with subtitles in case someone tries it.

https://codepen.io/raestrada/pen/rbZqQG

Thanks for taking the time.

**Comment by jthomerson** [comment]
It appears that you may be able to: https://developers.google.com/cast/docs/chrome_sender/advanced
