### ISSUE TITLE
Separate SCSS files according to function

### ISSUE THREAD

**Issue by yokuze** [silvermine/videojs-chromecast#5]
We should separate the main `videojs-chromecast.scss` file into 3 files:

1. `tech.scss` that contains all of the Video.js Chromecast Tech styles.
2. `chromecastButton.scss` that contains all of the Chromecast Button styles.
3. `videojs-chromecast.scss` that simply imports the first two files.

This way, users of this plugin can `@import` only the styles that they actually need. For example, someone may have their own Video.js skin that styles the Chromecast button, but still need the styling for the Tech (the screen that's displayed while Chromecast is connected / active).

This change would allow them to simply:

```scss
@import "silvermine-videojs-chromecast/src/scss/tech"
```

to get only the styles for the Tech and not have to override the button styles.

**Comment by onebytegone** [comment]
This was resolved with #6
