### ISSUE TITLE
Unsafe eval required in Content Security Policy

### ISSUE THREAD

**Issue by jandor64** [silvermine/videojs-chromecast#52]
When adding XSS protections, it looks like Class.extend requires unsafe-eval to be allowed. 

I have created a [CodePen](https://codepen.io/anon/pen/zVOvJr) to show this, the Content Security Policy is in the Settings of the pen. You can see the eval error in your browser console. 

I attempted to modify that code but didn't get very far, would be happy for your help!

**Comment by jthomerson** [comment]
Yeah, we hit this in one of our other repos, too. It came from [this commit](https://github.com/allenhwkim/class.extend/commit/5c82e983fe1adaa233d2bdf1fc81e517d3dbf15e) in class.extend, and IIRC, if you downgrade class.extend to 0.9.1, it's not there.

Please test downgrading, and find exactly which version introduced that commit, and then submit a PR to make that downgrade. We'll accept that.

Thanks!

**Comment by yokuze** [comment]
@jthomerson we can close this ticket now, I think.
