### ISSUE TITLE
Chromecast doesnot load the video

### ISSUE THREAD

**Issue by snj-adhikari** [silvermine/videojs-chromecast#58]
Hi , 
I am using videojs and videojs-chromecast with react for following site 

beamafilm.com. It shows the cast icon on video but when I try to cast movie it shows the blank screen, 

and doesnot load on tv.

**Comment by jthomerson** [comment]
@snj-adhikari Sorry, but we do not have the capacity to debug applications for our users. We are volunteers working on this project for free. If you'd like assistance, you will need to post a [minimal, complete, verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) (MCVE). Sometimes just by creating a MCVE you will actually discover the source of the problem yourself - or at least more details to help us reproduce it.

If you want some good examples of MCVE's, see a couple of issues that we have posted elsewhere, e.g:

 * https://github.com/videojs/video.js/issues/4765
 * https://github.com/videojs/http-streaming/issues/172

All of that detail is really important in getting help - especially on an open source plugin where people are donating their time. Without it we can't be sure what version of VideoJS you're using, or what other plugins you're using with it.

If you're able to reproduce the issue in an MCVE, post a comment here and the issue can be reopened.
