### ISSUE TITLE
Cannot find module declaration of 'webcomponents.js/webcomponents-lite'. 

### ISSUE THREAD

**Issue by Shihab-Github** [silvermine/videojs-chromecast#66]
After installing videojs-chromecast package in my react app when I try to build the project I get this error. 
**Cannot find module declaration of 'webcomponents.js/webcomponents-lite'.** 
This error throws in the preloadWebComponenets.js file which is located at this path --'npm_modules/@silvermine/videojs-chromecast/src/js/preloadWebcomponents.js' 

Any suggestion or help will be very much appreciated. Thanks

**Comment by jthomerson** [comment]
I don't know what to tell you. We declare `webcomponents.js` as a dependency, so it should be there. My first guess would be that you're using a packager that's not including it, maybe because the require statement is down in an `if` statement. You'll need to do some investigation for yourself to see if the package is installed and if it's getting bundled. If you have more detailed information after that and think it's a problem with this package, you can comment here asking for this to be reopened.

**Comment by Shihab-Github** [comment]
I didn’t write the if statement on that file. I just installed it using npm and after installation I tried to build my react app. But the build fails because it is unable to find the module that is specified in the require statement. My react app is created by the standard create-react-app command

**Comment by jthomerson** [comment]
I know you didn't write the `if` statement ... we did. It's part of our code.

What I'm saying is:

 * we declare the dependency for `webcomponents.js`, so when you `npm install`, it should be installed
 * it works for thousands of other people

So, it is most likely something unique to your environment. As mentioned in my previous comment, you'll need to do some debugging. For example:

 * is the `webcomponents.js` node package installed?
 * are you using any kind of bundler / packager like webpack? If so, is `webcomponents.js` bundled into the output? If it's not, then you might need to add some configuration to make sure that it gets bundled if your bundler isn't finding it.

That's all we can do for you.

**Comment by Shihab-Github** [comment]
Thanks a lot for your response. Can you please help me with this one thing, 

` "dependencies": {
    "class.extend": "0.9.1",
    "underscore": "1.8.3",
    "webcomponents.js": "git+https://git@github.com/webcomponents/webcomponentsjs.git#v0.7.24"
  },`

This dependencies object is taken from the package.json file which is located in silvermine-videojs-chromecast folder under node_modules directory. The value of 'webcomponent.js' key is I guess the source of error. If you check the provided url, you'll see that the repo has been moved out to another repo. Can you please guide me on it ? Thank you.

**Comment by jthomerson** [comment]
Although future development on the repo moved, the version that we're pointing to is still there.

What version of node and npm are you using? I just checked and this installs fine on node 8.10.0 and npm 6.4.1, but there are quite a few dependencies that don't install correctly at node 12.14.0 and npm 6.13.4.

Also, are you seeing errors when running `npm install`? My screen is filled with errors when I try to install it with the newer version of node/npm. That said, none of those errors cause the error you're reporting.

I will not be able to provide further assistance until you answer all the questions I've asked in this thread. Please see my previous comment and this comment for questions we'd need answers to before proceeding.
