### ISSUE TITLE
Player does not clear event listeners 

### ISSUE THREAD

**Issue by jenil** [silvermine/videojs-chromecast#67]
After the player is closed the event listeners are not cleared

![image](https://user-images.githubusercontent.com/971411/81357835-b8ef1780-90a2-11ea-81ad-1691c742bcde.png)

**Comment by jthomerson** [comment]
@jimjenkins5 did you recently work on an issue like this?

**Comment by tushroy** [comment]
I am also having this issue. Its happening after `player.dispose()` is called.

**Comment by alandrei** [comment]
This is still an issue. 
Furthermore I have another scenario. After starting casting if the player is disposed the casting session is not interrupted, which is fine, even if the above error is thrown, but when creating another player on the same session will show a player with a black screen that is completely unresponsive and the only work around I can think of is getting the current casting session and ending it some time in between the two videojs instances. Ideally the second player instance should be unaffected.

**Comment by dwassing** [comment]
@jthomerson by the way, I forgot to mention this issue in the latest pull request, if you want to close this.

It still seems strange to me how I did not pick up that the event listeners did not clear properly sooner...
