### ISSUE TITLE
Chromecast button shows even when no devices are available

### ISSUE THREAD

**Issue by yokuze** [silvermine/videojs-chromecast#7]
The [design guidelines for Chromecast sender apps](https://developers.google.com/cast/docs/design_checklist/cast-button#sender-cast-icon-states) says:

> While Cast receivers are not available, the Cast button does not appear.

Currently, the Chromecast button stays visible in the player, even when there are no devices available for Chromecast to connect to.

It's possible to detect Cast receiver availability using the [CastContext's getCastState function](https://developers.google.com/cast/docs/reference/chrome/cast.framework.CastContext#getCastState).

**Comment by onebytegone** [comment]
Closed by #8
