### ISSUE TITLE
VOD HLS stuck on high bitrate segments

### ISSUE THREAD

**Issue by ToishY** [silvermine/videojs-chromecast#72]
I've been experimenting with this plugin for a while now, and I have noticed that for HLS streams with TS segments (1920x1080 High@L4.0 AVC) with relatively high bitrate (30 Mbps), the chromecast tends to bug out (loading icon on TV keeps on spinning). The issue doesn't seem to occur until it hits segments with a bitrate of over +/- 12 Mbps. The segments play fine in the browser and it's still possible to skip the "troublesome" segments (while casting) in order to watch the rest of the video.

While I'm not entirely sure if this is a direct issue with the plugin, it seems more likely that the Chromecast just can't handle the segments. So I was wondering if anyone else also noticed this behaviour and/or knows what the max bitrate is that the Chromecast 3 (and Ultra) can handle? 

Anyway, if anyone can confirm this is indeed a problem with the Chromecast, I'll close this issue and head over to Google support. Thank you for your time.

**Comment by jthomerson** [comment]
Thanks for the detailed report @ToishY. Unfortunately, none of the core team on this project has experimented with HLS at that bitrate (that I'm aware of). But, we don't really do anything with the data stream, so I'd put odds on this being an issue with Chromecast directly. I'll close this issue for now, but if you do learn anything interesting with Google support, please post a comment here again if possible.

**Comment by ToishY** [comment]
Thank you for your reply @jthomerson. I've contacted the Google support and I got the following reply:

"Chromecast 3rd generation is capable of handling 1080p (60fps) and bit-rate for these resolutions is typically 8,000 kbps, therefore changing the bit-rate higher will affect the resolution while casting, however Chromecast Ultra is capable of handling 4K resolution and the bit-rate for this is typically from 35-45 Mbps. Yes, Chromecast  Ultra would be able to handle higher bit-rate videos compared to your current Chromecast 3rd generation."

It seems purchasing an Chromecast Ultra would solve the issue, but I'm just not convinced yet. 
The thing is, I just tested the same stream but now casting it using VLC, which to my surprise, didn't cause any issues. I was able to play the entire video without the chromecast getting stuck on the same high bitrate segments.

Now I don't want to jump to conclusions, and you may already know this, but it seems that there's a difference in casting from local players like VLC and webplayers. The only thing that's clear to me now, is that "something" fails to load high bitrate segments properly. What that something could, I just don't know. Maybe it's related to this plugin, or maybe something with `cast_sender.js`, or something else browser related. Anyway, I would love to figure out what's causing this.
