### ISSUE TITLE
Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by travisbader** [silvermine/videojs-chromecast#75]
Stacktrace attached below.  I attached as an image as the line highlighting is super helpful

![Screen Shot 2020-06-05 at 12 53 31 PM](https://user-images.githubusercontent.com/7252621/83917404-a57bae80-a72b-11ea-95f8-64094186bc16.png)

**Comment by jthomerson** [comment]
@travisbader those all appear to be in video.js code, not in this plugin's code. I'll close this issue for now. If you're able to create a [MRE](https://stackoverflow.com/help/minimal-reproducible-example) and link to it here, we can reopen the issue.

Examples of MRE's that we've made on other issues:
 * videojs/video.js#4765
 * videojs/http-streaming#172

**Comment by travisbader** [comment]
The cast_sender.js:81 threw me off.  Ill move it over to video.js. Thanks @jthomerson!
