### ISSUE TITLE
chromecast api is always undefined

### ISSUE THREAD

**Issue by davidboutet** [silvermine/videojs-chromecast#78]
Everything seem to be loader properly but no button added to the player.
ChromecastSessionManager.isChromecastAPIAvailable() always return undefined so it get stuck.

Im on Mac, with chrome 83.0.4103.61

Looks like property: **window.chrome.cast** is undefined

Am I doing something wrong?

**Comment by davidboutet** [comment]
My error, I wasnt running file from server.

**Comment by yucomds** [comment]
You saved my day! I do not know why but this plugin seems to work only on server, not work while developing  in localhost. Thanks

**Comment by wkhira** [comment]
@yucomds Hello, I believe I'm having the same issue. Could you please share how did you manage to solve it?
