### ISSUE TITLE
"ended" event does not fire at the end of the media item

### ISSUE THREAD

**Issue by yokuze** [silvermine/videojs-chromecast#9]
Sometimes the "ended" event does not fire when a media item ends. 

This means that the player will continue to show the Chromecast Tech even after the item has ended, instead of closing the Chromecast session after the `SESSION_TIMEOUT` is up.

This seems to be caused by [this `if` statement](https://github.com/silvermine/videojs-chromecast/blob/ebd31a01f375b48d6e924e606f310c16e4978674/src/js/tech/ChromecastTech.js#L514). The `PlayerState` is sometimes `null` after an item ends.

**Comment by onebytegone** [comment]
Closed by #10
