### ISSUE TITLE
I implemented all the code but chromecast button not showing in Vimeo video

### ISSUE THREAD

**Issue by udayankoliya** [silvermine/videojs-chromecast#94]
Here you can check my implemented code https://dev.strokeinfotech.com/pgvcl/

**Comment by matthewdickinson** [comment]
@udayankoliya For what it's worth, the chromecast button is showing up for me in your demo. Did you make a change to fix the issue you were encountering?

**Comment by udayankoliya** [comment]
@matthewdickinson Yes, I modified some code and the button is showing now. due to buttonPositionIndex its not showing properly.
